import { useEffect, useRef, useState } from "react";
import { Animated, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";

export type PatientPortalPreviewView = "providers" | "appointments" | "privacy/requests";
type Language = "sw" | "en";
type CareFilter = "nearby" | "online" | "pregnancy";

type PreviewProvider = {
  id: string;
  initials: string;
  name: string;
  titleSw: string;
  titleEn: string;
  location: string;
  mode: "clinic" | "online";
  focus: "general" | "pregnancy";
  nextSw: string;
  nextEn: string;
  price: string;
  tone: "rose" | "green" | "sand";
  slots: string[];
};

const providers: PreviewProvider[] = [
  { id: "neema", initials: "NS", name: "Dr Neema Said", titleSw: "Daktari wa afya ya uzazi", titleEn: "Obstetrician & gynaecologist", location: "Mkunazini, Zanzibar", mode: "clinic", focus: "pregnancy", nextSw: "Jumatano, 9:30 asubuhi", nextEn: "Wednesday, 9:30 AM", price: "TZS 45,000", tone: "rose", slots: ["09:30", "11:00", "15:30"] },
  { id: "rehema", initials: "RJ", name: "Rehema Joseph", titleSw: "Muuguzi mkunga", titleEn: "Nurse midwife", location: "Mwananyamala, Dar es Salaam", mode: "online", focus: "pregnancy", nextSw: "Leo, 4:30 jioni", nextEn: "Today, 4:30 PM", price: "TZS 25,000", tone: "green", slots: ["16:30", "17:15", "19:00"] },
  { id: "bahari", initials: "BW", name: "Bahari Women’s Clinic", titleSw: "Kliniki ya afya ya wanawake", titleEn: "Women’s health clinic", location: "Kinondoni, Dar es Salaam", mode: "clinic", focus: "general", nextSw: "Alhamisi, 10:00 asubuhi", nextEn: "Thursday, 10:00 AM", price: "TZS 35,000", tone: "sand", slots: ["10:00", "13:30", "16:00"] }
];

function tFor(language: Language, sw: string, en: string) {
  return language === "sw" ? sw : en;
}

function Icon({ children, tone = "green" }: { children: string; tone?: "green" | "rose" | "sand" }) {
  return <View accessible={false} style={[styles.icon, tone === "rose" && styles.iconRose, tone === "sand" && styles.iconSand]}><Text style={styles.iconText}>{children}</Text></View>;
}

function StatusNotice({ children }: { children: string }) {
  return <View accessibilityLiveRegion="polite" style={styles.notice}><Text style={styles.noticeIcon}>✓</Text><Text style={styles.noticeText}>{children}</Text></View>;
}

function CarePreview({ language, onNavigate }: { language: Language; onNavigate: (view: PatientPortalPreviewView) => void }) {
  const t = (sw: string, en: string) => tFor(language, sw, en);
  const [filter, setFilter] = useState<CareFilter>("nearby");
  const [query, setQuery] = useState("");
  const [selectedProvider, setSelectedProvider] = useState<PreviewProvider | null>(null);
  const [selectedSlot, setSelectedSlot] = useState("");

  const filtered = providers.filter((provider) => {
    const matchesFilter = filter === "nearby" || (filter === "online" ? provider.mode === "online" : provider.focus === "pregnancy");
    const searchable = `${provider.name} ${provider.titleEn} ${provider.titleSw} ${provider.location}`.toLowerCase();
    return matchesFilter && searchable.includes(query.trim().toLowerCase());
  });

  return <View>
    <View style={styles.pageHead}><View style={styles.flex}><Text style={styles.eyebrow}>{t("HUDUMA ILIYOTHIBITISHWA", "VERIFIED CARE")}</Text><Text accessibilityRole="header" style={styles.pageTitle}>{t("Huduma inayokufaa", "Care that fits your life")}</Text><Text style={styles.lead}>{t("Tafuta mtoa huduma, linganisha njia ya huduma na uone nafasi kabla ya kuweka miadi.", "Find a care professional, compare how care is delivered, and see availability before booking.")}</Text></View><View style={styles.previewPill}><Text style={styles.previewText}>{t("ONYESHO", "PREVIEW")}</Text></View></View>

    <View style={styles.searchBox}><Text style={styles.searchIcon}>⌕</Text><TextInput accessibilityLabel={t("Tafuta huduma", "Search care")} value={query} onChangeText={setQuery} placeholder={t("Tafuta jina, huduma au eneo", "Search name, service, or location")} placeholderTextColor="#7a8d87" style={styles.searchInput} /></View>
    <View accessibilityRole="tablist" style={styles.filterRow}>{([
      ["nearby", t("Karibu", "Nearby")],
      ["online", t("Mtandaoni", "Online")],
      ["pregnancy", t("Ujauzito", "Pregnancy")]
    ] as Array<[CareFilter, string]>).map(([value, label]) => <Pressable key={value} accessibilityRole="tab" accessibilityState={{ selected: filter === value }} onPress={() => { setFilter(value); setSelectedProvider(null); setSelectedSlot(""); }} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{label}</Text></Pressable>)}</View>

    <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>{t("CHAGUO ZAKO", "MATCHES FOR YOU")}</Text><Text style={styles.sectionTitle}>{filtered.length} {t("zinapatikana", "available")}</Text></View><Text style={styles.sortText}>{t("Nafasi ya karibu", "Soonest")}</Text></View>
    {filtered.length === 0 ? <View style={styles.emptyCard}><Text style={styles.emptyTitle}>{t("Hakuna huduma iliyolingana", "No matching care")}</Text><Text style={styles.body}>{t("Badili kichujio au neno la utafutaji.", "Try another filter or search term.")}</Text></View> : filtered.map((provider) => <View key={provider.id} style={styles.providerCard}>
      <View style={styles.providerTop}><View style={[styles.providerAvatar, provider.tone === "rose" && styles.providerAvatarRose, provider.tone === "sand" && styles.providerAvatarSand]}><Text style={styles.providerInitials}>{provider.initials}</Text></View><View style={styles.flex}><View style={styles.verifiedRow}><Text numberOfLines={1} style={styles.providerName}>{provider.name}</Text><Text accessibilityLabel={t("Amethibitishwa", "Verified")} style={styles.verifiedBadge}>✓</Text></View><Text style={styles.providerTitle}>{language === "sw" ? provider.titleSw : provider.titleEn}</Text><Text style={styles.location}>{provider.mode === "online" ? t("Mtandaoni", "Online") : provider.location} · {t("Kiswahili na Kiingereza", "English and Kiswahili")}</Text></View></View>
      <View style={styles.providerMeta}><View><Text style={styles.metaLabel}>{t("NAFASI IJAYO", "NEXT OPENING")}</Text><Text style={styles.metaValue}>{language === "sw" ? provider.nextSw : provider.nextEn}</Text></View><View style={styles.priceBlock}><Text style={styles.metaLabel}>{t("KUANZIA", "FROM")}</Text><Text style={styles.metaValue}>{provider.price}</Text></View></View>
      <Pressable accessibilityRole="button" onPress={() => { setSelectedProvider(provider); setSelectedSlot(""); }} style={({ pressed }) => [styles.outlineButton, pressed && styles.pressed]}><Text style={styles.outlineButtonText}>{t("Angalia nyakati", "View availability")}  →</Text></Pressable>
    </View>)}

    {selectedProvider ? <View accessibilityViewIsModal style={styles.availabilityCard}><View style={styles.modalHead}><View><Text style={styles.eyebrow}>{t("CHAGUA MUDA", "CHOOSE A TIME")}</Text><Text accessibilityRole="header" style={styles.sectionTitle}>{selectedProvider.name}</Text></View><Pressable accessibilityRole="button" accessibilityLabel={t("Funga", "Close")} onPress={() => { setSelectedProvider(null); setSelectedSlot(""); }} style={styles.closeButton}><Text style={styles.closeText}>×</Text></Pressable></View><Text style={styles.body}>{t("Jumatano, 16 Septemba · Saa za Afrika Mashariki", "Wednesday, 16 September · East Africa Time")}</Text><View style={styles.slotRow}>{selectedProvider.slots.map((slot) => <Pressable accessibilityRole="button" accessibilityState={{ selected: selectedSlot === slot }} key={slot} onPress={() => setSelectedSlot(slot)} style={[styles.slot, selectedSlot === slot && styles.slotSelected]}><Text style={[styles.slotText, selectedSlot === slot && styles.slotTextSelected]}>{slot}</Text></Pressable>)}</View>{selectedSlot ? <><StatusNotice>{t(`Umechagua ${selectedSlot}. Hakuna miadi halisi iliyowekwa kwenye onyesho.`, `${selectedSlot} selected. No real appointment is created in preview.`)}</StatusNotice><Pressable accessibilityRole="button" onPress={() => onNavigate("appointments")} style={styles.primaryButton}><Text style={styles.primaryButtonText}>{t("Kagua kwenye miadi", "Review in appointments")}</Text></Pressable></> : null}</View> : null}
  </View>;
}

function AppointmentsPreview({ language, onNavigate }: { language: Language; onNavigate: (view: PatientPortalPreviewView) => void }) {
  const t = (sw: string, en: string) => tFor(language, sw, en);
  const [tab, setTab] = useState<"upcoming" | "past">("upcoming");
  const [checked, setChecked] = useState<Set<string>>(new Set(["id"]));
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [changeOpen, setChangeOpen] = useState(false);
  const [newTime, setNewTime] = useState("");

  const toggleCheck = (item: string) => setChecked((current) => {
    const next = new Set(current);
    if (next.has(item)) next.delete(item); else next.add(item);
    return next;
  });

  return <View>
    <View style={styles.pageHead}><View style={styles.flex}><Text style={styles.eyebrow}>{t("RATIBA YANGU", "MY SCHEDULE")}</Text><Text accessibilityRole="header" style={styles.pageTitle}>{t("Miadi", "Appointments")}</Text><Text style={styles.lead}>{t("Maelezo, maandalizi na mabadiliko ya ziara katika sehemu moja.", "Visit details, preparation, and changes in one place.")}</Text></View><View style={styles.previewPill}><Text style={styles.previewText}>{t("ONYESHO", "PREVIEW")}</Text></View></View>
    <View accessibilityRole="tablist" style={styles.segment}><Pressable accessibilityRole="tab" accessibilityState={{ selected: tab === "upcoming" }} onPress={() => setTab("upcoming")} style={[styles.segmentButton, tab === "upcoming" && styles.segmentActive]}><Text style={[styles.segmentText, tab === "upcoming" && styles.segmentTextActive]}>{t("Ijayo", "Upcoming")}</Text></Pressable><Pressable accessibilityRole="tab" accessibilityState={{ selected: tab === "past" }} onPress={() => setTab("past")} style={[styles.segmentButton, tab === "past" && styles.segmentActive]}><Text style={[styles.segmentText, tab === "past" && styles.segmentTextActive]}>{t("Iliyopita", "Past")}</Text></Pressable></View>

    {tab === "upcoming" ? <>
      <View style={styles.appointmentHero}><View style={styles.appointmentDate}><Text style={styles.appointmentDay}>16</Text><Text style={styles.appointmentMonth}>{t("SEP", "SEP")}</Text></View><View style={styles.flex}><View style={styles.confirmedPill}><Text style={styles.confirmedText}>✓  {t("IMETHIBITISHWA", "CONFIRMED")}</Text></View><Text style={styles.appointmentTitle}>{t("Ziara ya kliniki ya wajawazito", "Antenatal visit")}</Text><Text style={styles.appointmentMeta}>{t("Jumatano · 9:30 asubuhi", "Wednesday · 9:30 AM")}</Text><Text style={styles.appointmentPlace}>Bahari Women’s Clinic · Mkunazini</Text></View></View>
      <View style={styles.actionRow}><Pressable accessibilityRole="button" onPress={() => setDetailsOpen((value) => !value)} style={styles.actionButton}><Text style={styles.actionIcon}>◇</Text><Text style={styles.actionText}>{detailsOpen ? t("Ficha maelezo", "Hide details") : t("Maelezo", "Details")}</Text></Pressable><Pressable accessibilityRole="button" onPress={() => { setChangeOpen((value) => !value); setNewTime(""); }} style={styles.actionButton}><Text style={styles.actionIcon}>↻</Text><Text style={styles.actionText}>{t("Badili muda", "Change time")}</Text></Pressable></View>
      {detailsOpen ? <View style={styles.detailCard}><Text style={styles.eyebrow}>{t("MAELEZO YA ZIARA", "VISIT DETAILS")}</Text><View style={styles.detailRow}><Text style={styles.detailLabel}>{t("Mtoa huduma", "Care professional")}</Text><Text style={styles.detailValue}>Dr Neema Said</Text></View><View style={styles.detailRow}><Text style={styles.detailLabel}>{t("Njia", "Mode")}</Text><Text style={styles.detailValue}>{t("Ana kwa ana", "In person")}</Text></View><View style={styles.detailRow}><Text style={styles.detailLabel}>{t("Gharama", "Price")}</Text><Text style={styles.detailValue}>TZS 45,000</Text></View></View> : null}
      {changeOpen ? <View style={styles.changeCard}><Text style={styles.eyebrow}>{t("NAFASI MBADALA", "ALTERNATIVE TIMES")}</Text><Text style={styles.sectionTitle}>{t("Chagua muda mpya", "Choose a new time")}</Text><View style={styles.slotRow}>{["11:00", "14:30", "16:00"].map((slot) => <Pressable accessibilityRole="button" accessibilityState={{ selected: newTime === slot }} key={slot} onPress={() => setNewTime(slot)} style={[styles.slot, newTime === slot && styles.slotSelected]}><Text style={[styles.slotText, newTime === slot && styles.slotTextSelected]}>{slot}</Text></Pressable>)}</View>{newTime ? <StatusNotice>{t(`Muda wa ${newTime} umechaguliwa kwa onyesho.`, `${newTime} selected for preview.`)}</StatusNotice> : null}</View> : null}
      <View style={styles.prepCard}><View style={styles.sectionHead}><View><Text style={styles.eyebrow}>{t("KABLA YA ZIARA", "BEFORE YOUR VISIT")}</Text><Text style={styles.sectionTitle}>{t("Umejiandaa kwa kiasi gani?", "Your preparation")}</Text></View><Text style={styles.prepCount}>{checked.size}/3</Text></View>{[
        ["id", t("Kitambulisho au namba ya mgonjwa", "ID or patient number")],
        ["questions", t("Andika maswali unayotaka kuuliza", "Note questions you want to ask")],
        ["medicines", t("Orodhesha dawa unazotumia", "Review medicines you take")]
      ].map(([id, label]) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: checked.has(id!) }} onPress={() => toggleCheck(id!)} key={id} style={styles.checkRow}><View style={[styles.checkbox, checked.has(id!) && styles.checkboxChecked]}><Text style={styles.checkboxText}>{checked.has(id!) ? "✓" : ""}</Text></View><Text style={[styles.checkLabel, checked.has(id!) && styles.checkLabelDone]}>{label}</Text></Pressable>)}</View>
      <Pressable accessibilityRole="button" onPress={() => onNavigate("providers")} style={styles.primaryButton}><Text style={styles.primaryButtonText}>＋  {t("Weka miadi nyingine", "Book another appointment")}</Text></Pressable>
    </> : <>
      <View style={styles.historyCard}><View style={styles.historyIcon}><Text style={styles.historyIconText}>✓</Text></View><View style={styles.flex}><Text style={styles.metaLabel}>{t("2 AGOSTI 2026", "2 AUGUST 2026")}</Text><Text style={styles.historyTitle}>{t("Ushauri wa afya ya wanawake", "Women’s health consultation")}</Text><Text style={styles.body}>Rehema Joseph · {t("Mtandaoni", "Online")}</Text></View></View>
      <View style={styles.historyCard}><View style={styles.historyIcon}><Text style={styles.historyIconText}>✓</Text></View><View style={styles.flex}><Text style={styles.metaLabel}>{t("18 JUNI 2026", "18 JUNE 2026")}</Text><Text style={styles.historyTitle}>{t("Ziara ya kawaida", "Routine visit")}</Text><Text style={styles.body}>Bahari Women’s Clinic · Kinondoni</Text></View></View>
    </>}
  </View>;
}

function SettingRow({ icon, title, detail, value, onChange }: { icon: string; title: string; detail: string; value: boolean; onChange: (value: boolean) => void }) {
  return <View style={styles.settingRow}><Icon>{icon}</Icon><View style={styles.flex}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingDetail}>{detail}</Text></View><Switch accessibilityLabel={title} value={value} onValueChange={onChange} trackColor={{ false: "#d8dedb", true: "#9cc8b7" }} thumbColor={value ? "#17665c" : "#71827d"} /></View>;
}

function AccountPreview({ language, onLanguageChange, onSignOut }: { language: Language; onLanguageChange: (language: Language) => void; onSignOut: () => void }) {
  const t = (sw: string, en: string) => tFor(language, sw, en);
  const [neutralNotifications, setNeutralNotifications] = useState(true);
  const [biometrics, setBiometrics] = useState(true);
  const [careSharing, setCareSharing] = useState(false);
  const [devicesOpen, setDevicesOpen] = useState(false);
  const [privacyOpen, setPrivacyOpen] = useState(false);
  const [deletionConfirm, setDeletionConfirm] = useState(false);
  const [notice, setNotice] = useState("");

  return <View>
    <View style={styles.pageHead}><View style={styles.flex}><Text style={styles.eyebrow}>{t("AKAUNTI YANGU", "MY ACCOUNT")}</Text><Text accessibilityRole="header" style={styles.pageTitle}>{t("Faragha na mapendeleo", "Privacy & preferences")}</Text><Text style={styles.lead}>{t("Dhibiti lugha, ruhusa, arifa na vifaa vinavyoweza kufungua taarifa zako.", "Control language, consent, notifications, and devices that can unlock your information.")}</Text></View><View style={styles.previewPill}><Text style={styles.previewText}>{t("ONYESHO", "PREVIEW")}</Text></View></View>
    {notice ? <StatusNotice>{notice}</StatusNotice> : null}
    <View style={styles.profileCard}><View style={styles.profileAvatar}><Text style={styles.profileInitials}>AM</Text></View><View style={styles.flex}><Text style={styles.profileName}>Amina M.</Text><Text style={styles.profileMeta}>{t("Mgonjwa · Zanzibar", "Patient · Zanzibar")}</Text><Text style={styles.profileVerified}>✓  {t("Barua pepe imethibitishwa", "Email verified")}</Text></View><Pressable accessibilityRole="button" onPress={() => setNotice(t("Uhariri wa wasifu utafunguliwa hapa.", "Profile editing will open here."))} style={styles.editButton}><Text style={styles.editText}>{t("Hariri", "Edit")}</Text></Pressable></View>

    <View style={styles.accountCard}><Text style={styles.eyebrow}>{t("LUGHA", "LANGUAGE")}</Text><Text style={styles.sectionTitle}>{t("Lugha ya programu", "App language")}</Text><View style={styles.languageRow}><Pressable accessibilityRole="radio" accessibilityState={{ checked: language === "sw" }} onPress={() => onLanguageChange("sw")} style={[styles.languageButton, language === "sw" && styles.languageButtonActive]}><Text style={[styles.languageText, language === "sw" && styles.languageTextActive]}>Kiswahili</Text></Pressable><Pressable accessibilityRole="radio" accessibilityState={{ checked: language === "en" }} onPress={() => onLanguageChange("en")} style={[styles.languageButton, language === "en" && styles.languageButtonActive]}><Text style={[styles.languageText, language === "en" && styles.languageTextActive]}>English</Text></Pressable></View></View>

    <View style={styles.accountCard}><Text style={styles.eyebrow}>{t("USALAMA NA FARAGHA", "SECURITY & PRIVACY")}</Text><SettingRow icon="◇" title={t("Fungua kwa biometriki", "Biometric unlock")} detail={t("Linda taarifa binafsi ukirudi kwenye programu", "Protect private information when returning to the app")} value={biometrics} onChange={setBiometrics} /><SettingRow icon="○" title={t("Arifa zisizoonyesha siri", "Discreet notifications")} detail={t("Onyesha ujumbe usio na maelezo ya afya", "Show neutral wording without health details")} value={neutralNotifications} onChange={setNeutralNotifications} /><SettingRow icon="♡" title={t("Shiriki muhtasari na mhudumu", "Share summary with care team")} detail={t("Imezimwa hadi utoe ruhusa ya wazi", "Off until you give explicit consent")} value={careSharing} onChange={setCareSharing} /></View>

    <Pressable accessibilityRole="button" accessibilityState={{ expanded: devicesOpen }} onPress={() => setDevicesOpen((value) => !value)} style={styles.menuCard}><Icon>▣</Icon><View style={styles.flex}><Text style={styles.menuTitle}>{t("Vifaa vyangu", "My devices")}</Text><Text style={styles.menuDetail}>{t("Kifaa 1 kinachoaminika", "1 trusted device")}</Text></View><Text style={styles.chevron}>{devicesOpen ? "⌃" : "›"}</Text></Pressable>
    {devicesOpen ? <View style={styles.deviceCard}><View style={styles.currentPill}><Text style={styles.currentText}>{t("KIFAA HIKI", "THIS DEVICE")}</Text></View><Text style={styles.deviceTitle}>iPhone 17 Pro</Text><Text style={styles.body}>{t("Ilitumika sasa · biometriki imewashwa", "Active now · biometric protection on")}</Text><Pressable accessibilityRole="button" onPress={() => setNotice(t("Kifaa hiki hakiwezi kuondolewa wakati kinatumika.", "This device cannot be revoked while it is active."))} style={styles.textButton}><Text style={styles.dangerText}>{t("Ondoa ruhusa ya kifaa", "Revoke device")}</Text></Pressable></View> : null}

    <Pressable accessibilityRole="button" accessibilityState={{ expanded: privacyOpen }} onPress={() => { setPrivacyOpen((value) => !value); setDeletionConfirm(false); }} style={styles.menuCard}><Icon>↧</Icon><View style={styles.flex}><Text style={styles.menuTitle}>{t("Nakala au kufuta taarifa", "Data copy or deletion")}</Text><Text style={styles.menuDetail}>{t("Dhibiti haki zako za taarifa", "Manage your information rights")}</Text></View><Text style={styles.chevron}>{privacyOpen ? "⌃" : "›"}</Text></Pressable>
    {privacyOpen ? <View style={styles.privacyCard}><Text style={styles.body}>{t("Ombi halitumi taarifa papo hapo. Timu ya faragha lazima ilithibitishe na kulishughulikia.", "A request does not send or delete information immediately. The privacy team must verify and process it.")}</Text><Pressable accessibilityRole="button" onPress={() => setNotice(t("Onyesho: ombi la nakala halikutumwa.", "Preview: data-copy request was not sent."))} style={styles.outlineButton}><Text style={styles.outlineButtonText}>{t("Omba nakala ya taarifa", "Request a data copy")}</Text></Pressable>{deletionConfirm ? <View style={styles.confirmCard}><Text style={styles.confirmTitle}>{t("Unataka kuona hatua ya uthibitisho?", "Preview the confirmation step?")}</Text><Text style={styles.body}>{t("Hakuna akaunti itakayofutwa kwenye onyesho hili.", "No account will be deleted in this preview.")}</Text><Pressable accessibilityRole="button" onPress={() => { setNotice(t("Onyesho: ombi la kufuta halikutumwa.", "Preview: deletion request was not sent.")); setDeletionConfirm(false); }} style={styles.dangerButton}><Text style={styles.dangerButtonText}>{t("Thibitisha onyesho", "Confirm preview")}</Text></Pressable></View> : <Pressable accessibilityRole="button" onPress={() => setDeletionConfirm(true)} style={styles.textButton}><Text style={styles.dangerText}>{t("Omba kufutwa kwa akaunti", "Request account deletion")}</Text></Pressable>}</View> : null}

    <Pressable accessibilityRole="button" onPress={onSignOut} style={styles.signOutButton}><Text style={styles.signOutText}>{t("Ondoka kwenye kifaa hiki", "Sign out of this device")}</Text></Pressable>
  </View>;
}

export function PatientPortalPreview({ language, view, onNavigate, onLanguageChange, onSignOut }: { language: Language; view: PatientPortalPreviewView; onNavigate: (view: PatientPortalPreviewView) => void; onLanguageChange: (language: Language) => void; onSignOut: () => void }) {
  const entrance = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    entrance.setValue(0);
    Animated.timing(entrance, { toValue: 1, duration: 360, useNativeDriver: true }).start();
  }, [entrance, view]);
  const style = { opacity: entrance, transform: [{ translateY: entrance.interpolate({ inputRange: [0, 1], outputRange: [10, 0] }) }] };
  return <Animated.View style={style}>{view === "providers" ? <CarePreview language={language} onNavigate={onNavigate} /> : view === "appointments" ? <AppointmentsPreview language={language} onNavigate={onNavigate} /> : <AccountPreview language={language} onLanguageChange={onLanguageChange} onSignOut={onSignOut} />}</Animated.View>;
}

const styles = StyleSheet.create({
  flex: { flex: 1, minWidth: 0 }, pageHead: { marginBottom: 20, flexDirection: "row", alignItems: "flex-start", gap: 10 }, eyebrow: { color: "#6e3b62", fontSize: 10, fontWeight: "900", letterSpacing: 1.2, marginBottom: 6 }, pageTitle: { color: "#173b37", fontSize: 35, lineHeight: 40, fontWeight: "700", letterSpacing: -1.1 }, lead: { color: "#5a706a", fontSize: 16, lineHeight: 23, marginTop: 7 }, body: { color: "#5b706a", fontSize: 13, lineHeight: 19 }, previewPill: { marginTop: 2, paddingHorizontal: 9, height: 27, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#efe8ed" }, previewText: { color: "#6e3b62", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] },
  searchBox: { minHeight: 54, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: "#cad8d1", borderRadius: 17, backgroundColor: "#fff", marginBottom: 12 }, searchIcon: { color: "#17665c", fontSize: 23, fontWeight: "700" }, searchInput: { flex: 1, color: "#173b37", fontSize: 15 }, filterRow: { flexDirection: "row", gap: 7, marginBottom: 22 }, filter: { minHeight: 44, flex: 1, paddingHorizontal: 8, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#d4dfd9", borderRadius: 22, backgroundColor: "#fff" }, filterActive: { borderColor: "#603653", backgroundColor: "#603653" }, filterText: { color: "#5f736d", fontSize: 11, fontWeight: "800" }, filterTextActive: { color: "#fff" },
  sectionHead: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 12 }, sectionTitle: { color: "#173b37", fontSize: 21, lineHeight: 26, fontWeight: "700" }, sortText: { color: "#61756f", fontSize: 11, fontWeight: "700" }, emptyCard: { padding: 22, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 20, backgroundColor: "#fff", marginBottom: 14 }, emptyTitle: { color: "#173b37", fontSize: 17, fontWeight: "800", marginBottom: 5 },
  providerCard: { padding: 18, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 22, backgroundColor: "#fff", marginBottom: 12, shadowColor: "#173b37", shadowOpacity: 0.04, shadowRadius: 14, shadowOffset: { width: 0, height: 6 } }, providerTop: { flexDirection: "row", alignItems: "flex-start", gap: 12 }, providerAvatar: { width: 52, height: 52, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: "#dcece5" }, providerAvatarRose: { backgroundColor: "#f1d8d7" }, providerAvatarSand: { backgroundColor: "#eadfcc" }, providerInitials: { color: "#603653", fontSize: 13, fontWeight: "900" }, verifiedRow: { flexDirection: "row", alignItems: "center", gap: 6 }, providerName: { flexShrink: 1, color: "#173b37", fontSize: 17, fontWeight: "800" }, verifiedBadge: { width: 19, height: 19, borderRadius: 10, color: "#fff", backgroundColor: "#17665c", textAlign: "center", lineHeight: 19, fontSize: 10, fontWeight: "900" }, providerTitle: { marginTop: 3, color: "#4b645d", fontSize: 13, lineHeight: 18 }, location: { marginTop: 4, color: "#74857f", fontSize: 10, lineHeight: 15 }, providerMeta: { marginTop: 16, paddingTop: 14, flexDirection: "row", justifyContent: "space-between", gap: 10, borderTopWidth: 1, borderTopColor: "#e2e7e4" }, priceBlock: { alignItems: "flex-end" }, metaLabel: { color: "#7a456f", fontSize: 8, fontWeight: "900", letterSpacing: 0.8, marginBottom: 4 }, metaValue: { color: "#173b37", fontSize: 12, fontWeight: "800" },
  outlineButton: { minHeight: 47, marginTop: 15, paddingHorizontal: 15, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#a9c5b9", borderRadius: 13, backgroundColor: "#fff" }, outlineButtonText: { color: "#17665c", fontSize: 13, fontWeight: "900", textAlign: "center" }, primaryButton: { minHeight: 50, marginTop: 14, paddingHorizontal: 17, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#603653" }, primaryButtonText: { color: "#fff", fontSize: 14, fontWeight: "900", textAlign: "center" },
  availabilityCard: { padding: 20, borderWidth: 1, borderColor: "#c8dbd2", borderRadius: 23, backgroundColor: "#edf6f2", marginBottom: 16 }, modalHead: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 12 }, closeButton: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#fff" }, closeText: { color: "#4f675f", fontSize: 24 }, slotRow: { flexDirection: "row", gap: 8, marginTop: 15 }, slot: { minHeight: 46, flex: 1, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#b9d0c6", borderRadius: 13, backgroundColor: "#fff" }, slotSelected: { borderColor: "#17665c", backgroundColor: "#17665c" }, slotText: { color: "#35554d", fontSize: 13, fontWeight: "900", fontVariant: ["tabular-nums"] }, slotTextSelected: { color: "#fff" }, notice: { marginTop: 13, padding: 13, flexDirection: "row", alignItems: "flex-start", gap: 8, borderRadius: 13, backgroundColor: "#dcece5" }, noticeIcon: { color: "#17665c", fontSize: 13, fontWeight: "900" }, noticeText: { flex: 1, color: "#31584e", fontSize: 11, lineHeight: 16 },
  segment: { marginBottom: 15, padding: 4, flexDirection: "row", borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 15, backgroundColor: "#fff" }, segmentButton: { minHeight: 44, flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 11 }, segmentActive: { backgroundColor: "#603653" }, segmentText: { color: "#62756f", fontSize: 12, fontWeight: "800" }, segmentTextActive: { color: "#fff" },
  appointmentHero: { padding: 20, flexDirection: "row", alignItems: "flex-start", gap: 15, borderRadius: 24, backgroundColor: "#173b37", marginBottom: 10 }, appointmentDate: { width: 63, height: 70, alignItems: "center", justifyContent: "center", borderRadius: 18, backgroundColor: "#dcece5" }, appointmentDay: { color: "#17665c", fontSize: 25, fontWeight: "900" }, appointmentMonth: { color: "#17665c", fontSize: 9, fontWeight: "900", letterSpacing: 1 }, confirmedPill: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: "rgba(220,236,229,.13)" }, confirmedText: { color: "#b9d9cd", fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, appointmentTitle: { marginTop: 9, color: "#fff", fontSize: 19, lineHeight: 24, fontWeight: "800" }, appointmentMeta: { marginTop: 6, color: "#d4e4df", fontSize: 13, fontWeight: "700" }, appointmentPlace: { marginTop: 4, color: "#9fb7b0", fontSize: 11, lineHeight: 16 }, actionRow: { flexDirection: "row", gap: 9, marginBottom: 14 }, actionButton: { minHeight: 64, flex: 1, alignItems: "center", justifyContent: "center", gap: 4, borderWidth: 1, borderColor: "#d6e0db", borderRadius: 17, backgroundColor: "#fff" }, actionIcon: { color: "#603653", fontSize: 18, fontWeight: "900" }, actionText: { color: "#36514a", fontSize: 11, fontWeight: "800" },
  detailCard: { padding: 18, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 20, backgroundColor: "#fff", marginBottom: 14 }, detailRow: { paddingVertical: 10, flexDirection: "row", justifyContent: "space-between", gap: 10, borderTopWidth: 1, borderTopColor: "#e2e7e4" }, detailLabel: { color: "#6c7e78", fontSize: 12 }, detailValue: { color: "#173b37", fontSize: 12, fontWeight: "800", textAlign: "right" }, changeCard: { padding: 18, borderWidth: 1, borderColor: "#d8c8d5", borderRadius: 20, backgroundColor: "#f5eff4", marginBottom: 14 },
  prepCard: { padding: 20, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 22, backgroundColor: "#fff", marginBottom: 14 }, prepCount: { color: "#17665c", fontSize: 24, fontWeight: "900" }, checkRow: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 11, borderTopWidth: 1, borderTopColor: "#e2e7e4" }, checkbox: { width: 28, height: 28, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#b9cbc3", borderRadius: 9 }, checkboxChecked: { borderColor: "#17665c", backgroundColor: "#dcece5" }, checkboxText: { color: "#17665c", fontSize: 14, fontWeight: "900" }, checkLabel: { flex: 1, color: "#334e47", fontSize: 13, lineHeight: 18, fontWeight: "700" }, checkLabelDone: { color: "#72827d", textDecorationLine: "line-through" }, historyCard: { padding: 18, flexDirection: "row", gap: 12, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 20, backgroundColor: "#fff", marginBottom: 12 }, historyIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#dcece5" }, historyIconText: { color: "#17665c", fontSize: 17, fontWeight: "900" }, historyTitle: { color: "#173b37", fontSize: 16, fontWeight: "800", marginBottom: 4 },
  icon: { width: 43, height: 43, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#e5f1eb" }, iconRose: { backgroundColor: "#f3dedd" }, iconSand: { backgroundColor: "#eee3d1" }, iconText: { color: "#603653", fontSize: 18, fontWeight: "900" }, profileCard: { padding: 18, flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 22, backgroundColor: "#fff", marginBottom: 14 }, profileAvatar: { width: 55, height: 55, alignItems: "center", justifyContent: "center", borderRadius: 19, backgroundColor: "#eadde7" }, profileInitials: { color: "#603653", fontSize: 14, fontWeight: "900" }, profileName: { color: "#173b37", fontSize: 18, fontWeight: "900" }, profileMeta: { marginTop: 3, color: "#647770", fontSize: 11 }, profileVerified: { marginTop: 5, color: "#17665c", fontSize: 10, fontWeight: "800" }, editButton: { minHeight: 44, paddingHorizontal: 10, alignItems: "center", justifyContent: "center" }, editText: { color: "#603653", fontSize: 12, fontWeight: "900" },
  accountCard: { padding: 19, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 22, backgroundColor: "#fff", marginBottom: 14 }, languageRow: { marginTop: 14, padding: 4, flexDirection: "row", borderWidth: 1, borderColor: "#d8e1dc", borderRadius: 14 }, languageButton: { minHeight: 43, flex: 1, alignItems: "center", justifyContent: "center", borderRadius: 10 }, languageButtonActive: { backgroundColor: "#603653" }, languageText: { color: "#5d716b", fontSize: 12, fontWeight: "800" }, languageTextActive: { color: "#fff" }, settingRow: { minHeight: 76, flexDirection: "row", alignItems: "center", gap: 11, borderTopWidth: 1, borderTopColor: "#e2e7e4" }, settingTitle: { color: "#173b37", fontSize: 13, fontWeight: "800" }, settingDetail: { marginTop: 3, color: "#6b7d77", fontSize: 10, lineHeight: 15 },
  menuCard: { minHeight: 76, padding: 16, flexDirection: "row", alignItems: "center", gap: 12, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 20, backgroundColor: "#fff", marginBottom: 10 }, menuTitle: { color: "#173b37", fontSize: 14, fontWeight: "800" }, menuDetail: { marginTop: 3, color: "#6b7d77", fontSize: 10 }, chevron: { color: "#6e3b62", fontSize: 25, fontWeight: "400" }, deviceCard: { padding: 18, borderWidth: 1, borderColor: "#c8dbd2", borderRadius: 19, backgroundColor: "#edf6f2", marginTop: -3, marginBottom: 12 }, currentPill: { alignSelf: "flex-start", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9, backgroundColor: "#d4e8df" }, currentText: { color: "#17665c", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 }, deviceTitle: { marginTop: 10, color: "#173b37", fontSize: 16, fontWeight: "900" }, textButton: { minHeight: 45, alignSelf: "flex-start", justifyContent: "center" }, dangerText: { color: "#9b3b35", fontSize: 12, fontWeight: "900" }, privacyCard: { padding: 18, borderWidth: 1, borderColor: "#d9e1dc", borderRadius: 19, backgroundColor: "#fff", marginTop: -3, marginBottom: 12 }, confirmCard: { marginTop: 12, padding: 14, borderRadius: 14, backgroundColor: "#fff0ed" }, confirmTitle: { color: "#642f2b", fontSize: 14, fontWeight: "900", marginBottom: 4 }, dangerButton: { minHeight: 47, marginTop: 10, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#a33c35" }, dangerButtonText: { color: "#fff", fontSize: 12, fontWeight: "900" }, signOutButton: { minHeight: 50, marginTop: 5, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#d7dfda", borderRadius: 14, backgroundColor: "#fff" }, signOutText: { color: "#344d48", fontSize: 13, fontWeight: "900" }
});
