import { useEffect, useRef, useState } from "react";
import { Animated, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { MedicationRemindersScreen, MedicationSummaryCard, useMedicineReminders } from "@/components/MedicationReminders";
import { PrivatePatientTracker } from "@/components/PrivatePatientTracker";

export type PatientTrackerView = "personal" | "cycle" | "pregnancy" | "reminders";
type Language = "sw" | "en";
type LifeStage = "cycle" | "pregnancy" | "postpartum" | "perimenopause";

const cycleDays = [9, 10, 11, 12, 13, 14, 15];

function Glyph({ children, tone = "plum" }: { children: string; tone?: "plum" | "green" | "rose" }) {
  return <View accessible={false} style={[styles.glyph, tone === "green" && styles.glyphGreen, tone === "rose" && styles.glyphRose]}><Text style={styles.glyphText}>{children}</Text></View>;
}

function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) {
  return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => [styles.choice, selected && styles.choiceSelected, pressed && styles.pressed]}><Text style={[styles.choiceText, selected && styles.choiceTextSelected]}>{label}</Text></Pressable>;
}

export function PatientTracker(props: Parameters<typeof PatientTrackerPreview>[0]) {
  return props.preview ? <PatientTrackerPreview {...props} /> : <PrivatePatientTracker {...props} />;
}

function PatientTrackerPreview({
  language,
  view,
  onNavigate,
  onOpenAppointments,
  onBrowseCare,
  storageScope,
  preview
}: {
  language: Language;
  view: PatientTrackerView;
  onNavigate: (view: PatientTrackerView) => void;
  onOpenAppointments: () => void;
  onBrowseCare: () => void;
  storageScope: string;
  preview: boolean;
}) {
  const t = (sw: string, en: string) => language === "sw" ? sw : en;
  const entrance = useRef(new Animated.Value(0)).current;
  const [stage, setStage] = useState<LifeStage>(view === "pregnancy" ? "pregnancy" : "cycle");
  const [flow, setFlow] = useState("none");
  const [mood, setMood] = useState("steady");
  const [symptoms, setSymptoms] = useState<Set<string>>(new Set(["cramps"]));
  const [saved, setSaved] = useState(false);
  const [urgentOpen, setUrgentOpen] = useState(false);
  const [selectedDay, setSelectedDay] = useState(14);
  const medicineReminders = useMedicineReminders({ language, storageScope, preview });

  useEffect(() => {
    entrance.setValue(0);
    Animated.timing(entrance, { toValue: 1, duration: 420, useNativeDriver: true }).start();
  }, [entrance, view]);

  const enterStyle = {
    opacity: entrance,
    transform: [{ translateY: entrance.interpolate({ inputRange: [0, 1], outputRange: [12, 0] }) }]
  };

  const toggleSymptom = (value: string) => {
    setSaved(false);
    setSymptoms((current) => {
      const next = new Set(current);
      if (value === "none") return new Set(["none"]);
      next.delete("none");
      if (next.has(value)) next.delete(value);
      else next.add(value);
      return next;
    });
  };

  const stageLabels: Array<[LifeStage, string]> = [
    ["cycle", t("Mzunguko", "Cycle")],
    ["pregnancy", t("Ujauzito", "Pregnancy")],
    ["postpartum", t("Baada ya kujifungua", "Postpartum")],
    ["perimenopause", t("Ukomo wa hedhi", "Perimenopause")]
  ];
  const stageCopy: Record<LifeStage, { eyebrow: string; title: string; detail: string; glyph: string }> = {
    cycle: { eyebrow: t("MZUNGUKO WANGU", "MY CYCLE"), title: t("Siku ya 13", "Cycle day 13"), detail: t("Hedhi inakadiriwa baada ya siku 15–18", "Period estimated in 15–18 days"), glyph: "●" },
    pregnancy: { eyebrow: t("UJAUZITO WANGU", "MY PREGNANCY"), title: t("Wiki 24 + siku 3", "24 weeks + 3 days"), detail: t("Muhula wa pili · tarehe 29 Desemba", "Second trimester · due 29 December"), glyph: "♡" },
    postpartum: { eyebrow: t("KUPONA KWANGU", "MY RECOVERY"), title: t("Wiki ya 5", "Recovery week 5"), detail: t("Hisia, usingizi, ulishaji na kupona", "Mood, sleep, feeding, and recovery"), glyph: "⌁" },
    perimenopause: { eyebrow: t("MWENENDO WANGU", "MY PATTERNS"), title: t("Muhtasari wa siku 30", "Your 30-day view"), detail: t("Usingizi, joto la mwili na hisia", "Sleep, hot flushes, and mood"), glyph: "≈" }
  };

  const quickLog = <View style={styles.card}>
    <View style={styles.sectionHead}><View><Text style={styles.eyebrow}>{t("DAKIKA MOJA", "ONE MINUTE")}</Text><Text accessibilityRole="header" style={styles.cardTitle}>{t("Ukoje leo?", "How are you today?")}</Text></View><Text style={styles.mutedSmall}>14 Sep</Text></View>
    <View style={styles.logBlock}><Text style={styles.logLabel}>{t("Mtiririko", "Flow")}</Text><View style={styles.wrap}>{([ ["none", t("Hakuna", "None")], ["light", t("Kidogo", "Light")], ["medium", t("Wastani", "Medium")], ["heavy", t("Mwingi", "Heavy")] ] as Array<[string, string]>).map(([value, label]) => <Choice key={value} label={label} selected={flow === value} onPress={() => { setFlow(value); setSaved(false); }} />)}</View></View>
    <View style={styles.logBlock}><Text style={styles.logLabel}>{t("Hisia", "Mood")}</Text><View style={styles.moodRow}>{([ ["low", "○", t("Chini", "Low")], ["steady", "◡", t("Sawa", "Steady")], ["good", "⌣", t("Nzuri", "Good")], ["great", "✦", t("Bora", "Great")] ] as Array<[string, string, string]>).map(([value, symbol, label]) => <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected: mood === value }} key={value} onPress={() => { setMood(value); setSaved(false); }} style={({ pressed }) => [styles.mood, mood === value && styles.moodSelected, pressed && styles.pressed]}><Text style={styles.moodSymbol}>{symbol}</Text><Text style={[styles.moodLabel, mood === value && styles.choiceTextSelected]}>{label}</Text></Pressable>)}</View></View>
    <View style={styles.logBlock}><Text style={styles.logLabel}>{t("Dalili", "Symptoms")}</Text><View style={styles.wrap}>{([ ["cramps", t("Tumbo", "Cramps")], ["headache", t("Kichwa", "Headache")], ["bloating", t("Kuvimba", "Bloating")], ["backache", t("Mgongo", "Backache")], ["none", t("Hakuna", "None")] ] as Array<[string, string]>).map(([value, label]) => <Choice key={value} label={`${symptoms.has(value) ? "✓" : "+"}  ${label}`} selected={symptoms.has(value)} onPress={() => toggleSymptom(value)} />)}</View></View>
    <Pressable accessibilityRole="button" onPress={() => setSaved(true)} style={({ pressed }) => [styles.primaryButton, pressed && styles.pressed]}><Text style={styles.primaryButtonText}>{saved ? `✓  ${t("Imehifadhiwa kwa kipindi hiki", "Saved for this session")}` : `+  ${t("Hifadhi kumbukumbu ya leo", "Save today’s check-in")}`}</Text></Pressable>
    <View style={styles.privateNote}><Text style={styles.privateNoteIcon}>◇</Text><Text style={styles.privateNoteText}>{t("Onyesho hili halishiriki kumbukumbu na mhudumu.", "This preview does not share entries with care professionals.")}</Text></View>
  </View>;

  if (view === "reminders") return <Animated.View style={[styles.screen, enterStyle]}>
    <MedicationRemindersScreen language={language} controller={medicineReminders} onBack={() => onNavigate("personal")} />
  </Animated.View>;

  if (view === "cycle") return <Animated.View style={[styles.screen, enterStyle]}>
    <View style={styles.pageHead}><Text style={styles.eyebrow}>{t("MZUNGUKO WANGU", "MY CYCLE")}</Text><Text accessibilityRole="header" style={styles.pageTitle}>{t("Kalenda na mienendo", "Calendar & patterns")}</Text><Text style={styles.lead}>{t("Kumbukumbu, makadirio na mabadiliko yako kwa mtazamo mmoja.", "Your entries, estimates, and changes at a glance.")}</Text></View>
    <View style={[styles.card, styles.cycleHero]}><View style={styles.cycleRing}><Text style={styles.cycleNumber}>13</Text><Text style={styles.cycleUnit}>{t("SIKU", "DAY")}</Text></View><View style={styles.flex}><Text style={styles.eyebrow}>{t("LEO", "TODAY")}</Text><Text style={styles.cardTitle}>{t("Awamu ya ukuaji", "Follicular phase")}</Text><Text style={styles.bodySmall}>{t("Nguvu inaweza kuongezeka katika siku zinazofuata.", "Energy may rise over the next few days.")}</Text></View></View>
    <View style={styles.card}><View style={styles.sectionHead}><View><Text style={styles.eyebrow}>{t("SEPTEMBA 2026", "SEPTEMBER 2026")}</Text><Text style={styles.cardTitle}>{t("Wiki hii", "This week")}</Text></View><Text style={styles.chevron}>›</Text></View><View style={styles.weekRow}>{cycleDays.map((day, index) => <Pressable accessibilityRole="button" accessibilityState={{ selected: selectedDay === day }} onPress={() => setSelectedDay(day)} key={day} style={[styles.day, day === 14 && styles.dayToday, (day === 13 || day === 15) && styles.dayFertile, selectedDay === day && day !== 14 && styles.daySelected]}><Text style={[styles.dayName, day === 14 && styles.dayTextSelected]}>{(language === "sw" ? ["J4", "J5", "Al", "Ij", "Jp", "J2", "J3"] : ["W", "T", "F", "S", "S", "M", "T"])[index]}</Text><Text style={[styles.dayNumber, day === 14 && styles.dayTextSelected]}>{day}</Text></Pressable>)}</View><View style={styles.legend}><Text style={styles.legendText}>●  {t("Leo", "Today")}</Text><Text style={styles.legendTextGreen}>●  {t("Rutuba inayokadiriwa", "Estimated fertile")}</Text></View></View>
    <View style={styles.statsRow}><View style={styles.stat}><Text numberOfLines={1} style={styles.statValue}>29</Text><Text adjustsFontSizeToFit minimumFontScale={0.7} numberOfLines={2} style={styles.statLabel}>{t("WASTANI WA SIKU", "DAY AVERAGE")}</Text></View><View style={styles.stat}><Text numberOfLines={1} style={styles.statValue}>5</Text><Text adjustsFontSizeToFit minimumFontScale={0.7} numberOfLines={2} style={styles.statLabel}>{t("SIKU ZA HEDHI", "PERIOD DAYS")}</Text></View><View style={styles.stat}><Text numberOfLines={1} style={styles.statValue}>3</Text><Text adjustsFontSizeToFit minimumFontScale={0.7} numberOfLines={2} style={styles.statLabel}>{t("MIZUNGUKO", "CYCLES LOGGED")}</Text></View></View>
    <View style={styles.card}><Text style={styles.eyebrow}>{t("MWENENDO", "PATTERN")}</Text><Text style={styles.cardTitle}>{t("Nguvu kwa siku 7", "Energy over 7 days")}</Text><View style={styles.barChart}>{[32, 47, 39, 59, 70, 82, 72].map((height, index) => <View key={index} style={[styles.bar, { height }]} />)}</View><Text style={styles.bodySmall}>{t("Nguvu huwa juu baada ya hedhi katika mizunguko yako mitatu ya mwisho.", "Energy tends to rise after your period across your last three cycles.")}</Text></View>
    <View style={styles.disclaimer}><Text style={styles.disclaimerIcon}>!</Text><Text style={styles.disclaimerText}>{t("Makadirio si uchunguzi wa ugonjwa na yasitumike kuzuia mimba.", "Predictions are not a diagnosis and must not be used as contraception.")}</Text></View>
    <Pressable accessibilityRole="button" onPress={() => onNavigate("personal")} style={styles.primaryButton}><Text style={styles.primaryButtonText}>{t("Rekodi leo", "Log today")}</Text></Pressable>
  </Animated.View>;

  if (view === "pregnancy") return <Animated.View style={[styles.screen, enterStyle]}>
    <View style={styles.pageHead}><Text style={styles.eyebrow}>{t("UJAUZITO WANGU", "MY PREGNANCY")}</Text><Text accessibilityRole="header" style={styles.pageTitle}>{t("Wiki 24, kwa utulivu", "Week 24, at a glance")}</Text><Text style={styles.lead}>{t("Hatua, ziara na vitu muhimu vya leo.", "Your stage, visits, and today’s essentials.")}</Text></View>
    <View style={styles.pregnancyHero}><View style={styles.pregnancyTop}><Glyph tone="green">♡</Glyph><View style={styles.percentPill}><Text style={styles.percentText}>61%</Text></View></View><Text style={styles.pregnancyLabel}>{t("MUHULA WA PILI", "SECOND TRIMESTER")}</Text><Text style={styles.pregnancyTitle}>{t("Wiki 24 + siku 3", "24 weeks + 3 days")}</Text><Text style={styles.pregnancyDate}>{t("Tarehe inayokadiriwa: 29 Desemba 2026", "Estimated due date: 29 December 2026")}</Text><View style={styles.progress}><View style={styles.progressFill} /></View><Text style={styles.pregnancyNote}>{t("Makadirio yanaweza kubadilika. Mhudumu wako atathibitisha tarehe za huduma.", "Estimates can change. Your care professional will confirm clinical dates.")}</Text></View>
    <MedicationSummaryCard language={language} controller={medicineReminders} onOpen={() => onNavigate("reminders")} />
    <Pressable accessibilityRole="button" onPress={onOpenAppointments} style={({ pressed }) => [styles.card, styles.appointmentCard, pressed && styles.pressed]}><Glyph tone="green">＋</Glyph><View style={styles.flex}><Text style={styles.eyebrow}>{t("HUDUMA IJAYO · SIKU 2", "NEXT CARE · 2 DAYS")}</Text><Text style={styles.cardTitle}>{t("Ziara ya kliniki ya wajawazito", "Antenatal visit")}</Text><Text style={styles.bodySmall}>{t("Jumatano · 3:30 asubuhi · Mkunazini", "Wednesday · 9:30 AM · Mkunazini")}</Text></View><Text style={styles.chevron}>›</Text></Pressable>
    <View style={styles.card}><View style={styles.sectionHead}><View><Text style={styles.eyebrow}>{t("MPANGO WA HUDUMA", "CARE PLAN")}</Text><Text style={styles.cardTitle}>{t("Ziara 8 za kliniki", "8 antenatal contacts")}</Text></View><Text style={styles.planCount}>3/8</Text></View><View style={styles.contactRow}>{[1,2,3,4,5,6,7,8].map(item => <View key={item} style={[styles.contact, item <= 3 && styles.contactDone]}><Text style={[styles.contactText, item <= 3 && styles.contactTextDone]}>{item <= 3 ? "✓" : item}</Text></View>)}</View><Text style={styles.bodySmall}>{t("Ratiba hii inafuata mfano wa WHO. Mhudumu wako anaweza kuibadilisha kulingana na mahitaji yako.", "This follows the WHO model. Your care professional may adjust it for your needs.")}</Text></View>
    <View style={styles.card}><Text style={styles.eyebrow}>{t("LEO", "TODAY")}</Text><Text style={styles.cardTitle}>{t("Vitu vitatu vya kuzingatia", "Three gentle priorities")}</Text>{[["✓", t("Dawa na virutubisho", "Medicine & supplements")], ["◡", t("Usingizi na nguvu", "Sleep & energy")], ["♡", t("Harakati za mtoto", "Baby movement")]].map(([glyph, label]) => <View key={label} style={styles.priority}><Glyph tone="green">{glyph!}</Glyph><Text style={styles.priorityText}>{label}</Text></View>)}</View>
    <View style={styles.dangerCard}><Glyph tone="rose">!</Glyph><View style={styles.flex}><Text style={styles.dangerLabel}>{t("USISUBIRI", "DO NOT WAIT")}</Text><Text style={styles.dangerTitle}>{t("Una dalili ya hatari?", "Do you have a danger sign?")}</Text><Text style={styles.dangerBody}>{t("Kutokwa damu, degedege, maumivu makali ya kichwa, kupumua kwa shida, maumivu makali ya tumbo au kupungua kwa harakati za mtoto kunahitaji huduma ya haraka.", "Bleeding, seizures, severe headache, difficulty breathing, severe abdominal pain, or reduced baby movement needs urgent assessment.")}</Text><Pressable accessibilityRole="button" onPress={() => setUrgentOpen(true)} style={styles.dangerButton}><Text style={styles.dangerButtonText}>{t("Nahitaji msaada sasa", "I need help now")}</Text></Pressable></View></View>
    {urgentOpen ? <View accessibilityViewIsModal style={styles.urgentSheet}><Text style={styles.urgentIcon}>!</Text><Text accessibilityRole="header" style={styles.urgentTitle}>{t("Tafuta huduma ya haraka sasa", "Get urgent medical care now")}</Text><Text style={styles.lead}>{t("Nenda hospitali au kituo cha afya kilicho karibu. Ukiweza, mwombe mtu unayemwamini akusindikize. MWANAMKE si huduma ya dharura.", "Go to the nearest hospital or health facility. If possible, ask someone you trust to accompany you. MWANAMKE is not an emergency service.")}</Text><Pressable accessibilityRole="button" onPress={onBrowseCare} style={styles.dangerButton}><Text style={styles.dangerButtonText}>{t("Tafuta kituo cha huduma", "Find a care facility")}</Text></Pressable><Pressable accessibilityRole="button" onPress={() => setUrgentOpen(false)} style={styles.secondaryButton}><Text style={styles.secondaryButtonText}>{t("Funga", "Close")}</Text></Pressable></View> : null}
  </Animated.View>;

  const active = stageCopy[stage];
  return <Animated.View style={[styles.screen, enterStyle]}>
    <View style={styles.homeHead}><View><Text style={styles.date}>{t("JUMATATU, 14 SEPTEMBA", "MONDAY, 14 SEPTEMBER")}</Text><Text accessibilityRole="header" style={styles.pageTitle}>{t("Habari, Amina", "Hello, Amina")}</Text><Text style={styles.lead}>{t("Haya ndiyo muhimu kwako leo.", "Here’s what matters for you today.")}</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>AM</Text></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.stageTabs}>{stageLabels.map(([value, label]) => <Pressable accessibilityRole="tab" accessibilityState={{ selected: stage === value }} key={value} onPress={() => setStage(value)} style={[styles.stageTab, stage === value && styles.stageTabActive]}><Text style={[styles.stageTabText, stage === value && styles.stageTabTextActive]}>{label}</Text></Pressable>)}</ScrollView>
    <View style={[styles.stageHero, stage === "pregnancy" && styles.stageHeroGreen, stage === "postpartum" && styles.stageHeroSand, stage === "perimenopause" && styles.stageHeroLilac]}><View style={styles.stageHeroTop}><Text style={styles.stageEyebrow}>{active.eyebrow}</Text><Glyph tone={stage === "pregnancy" ? "green" : "plum"}>{active.glyph}</Glyph></View><Text style={styles.stageTitle}>{active.title}</Text><Text style={styles.stageDetail}>{active.detail}</Text>{stage === "cycle" || stage === "pregnancy" ? <Pressable accessibilityRole="button" onPress={() => onNavigate(stage === "pregnancy" ? "pregnancy" : "cycle")} style={styles.heroButton}><Text style={styles.heroButtonText}>{stage === "pregnancy" ? t("Fungua ratiba ya ujauzito", "Open pregnancy timeline") : t("Fungua kalenda", "Open calendar")}  →</Text></Pressable> : null}<View style={styles.heroOrbOne} /><View style={styles.heroOrbTwo} /></View>
    <MedicationSummaryCard language={language} controller={medicineReminders} onOpen={() => onNavigate("reminders")} />
    {quickLog}
    <Pressable accessibilityRole="button" onPress={() => onNavigate("cycle")} style={({ pressed }) => [styles.insightCard, pressed && styles.pressed]}><Glyph>≈</Glyph><View style={styles.flex}><Text style={styles.eyebrow}>{t("MWENENDO WAKO", "YOUR PATTERN")}</Text><Text style={styles.insightTitle}>{t("Nguvu huwa juu baada ya hedhi", "Energy tends to rise after your period")}</Text><Text style={styles.bodySmall}>{t("Imeonekana katika mizunguko 3 iliyopita.", "Seen across your last 3 cycles.")}</Text></View><Text style={styles.chevron}>›</Text></Pressable>
    <Pressable accessibilityRole="button" onPress={onOpenAppointments} style={({ pressed }) => [styles.card, styles.appointmentCard, pressed && styles.pressed]}><Glyph tone="green">＋</Glyph><View style={styles.flex}><Text style={styles.eyebrow}>{t("MIADI IJAYO", "NEXT APPOINTMENT")}</Text><Text style={styles.appointmentTitle}>{t("Jumatano · 3:30 asubuhi", "Wednesday · 9:30 AM")}</Text><Text style={styles.bodySmall}>{t("Kliniki ya Wanawake Bahari", "Bahari Women’s Clinic")}</Text></View><Text style={styles.chevron}>›</Text></Pressable>
    <View style={styles.privacyStrip}><Text style={styles.privateNoteIcon}>◇</Text><View style={styles.flex}><Text style={styles.privacyTitle}>{t("Kumbukumbu zako ni binafsi", "Your entries are private")}</Text><Text style={styles.privateNoteText}>{t("Hakuna mhudumu anayeweza kuziona bila ruhusa yako ya wazi.", "No care professional can see them without your explicit consent.")}</Text></View></View>
  </Animated.View>;
}

const styles = StyleSheet.create({
  screen:{paddingBottom:8}, pageHead:{marginBottom:22}, homeHead:{marginBottom:20,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:14}, flex:{flex:1,minWidth:0}, date:{color:"#7a456f",fontSize:11,fontWeight:"800",letterSpacing:1.3,marginBottom:8}, pageTitle:{color:"#173b37",fontSize:35,lineHeight:40,fontWeight:"700",letterSpacing:-1.1}, lead:{color:"#5a706a",fontSize:16,lineHeight:23,marginTop:6}, avatar:{width:48,height:48,borderRadius:17,alignItems:"center",justifyContent:"center",backgroundColor:"#eadde7"}, avatarText:{color:"#613757",fontSize:13,fontWeight:"800"},
  eyebrow:{color:"#6e3b62",fontSize:10,fontWeight:"800",letterSpacing:1.15,marginBottom:6}, card:{padding:20,borderWidth:1,borderColor:"#d9e1dc",borderRadius:22,backgroundColor:"#fff",marginBottom:14,shadowColor:"#173b37",shadowOpacity:.045,shadowRadius:14,shadowOffset:{width:0,height:6}}, cardTitle:{color:"#173b37",fontSize:21,lineHeight:26,fontWeight:"700"}, sectionHead:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:12}, mutedSmall:{color:"#71827d",fontSize:12}, bodySmall:{color:"#5b706a",fontSize:14,lineHeight:20},
  stageTabs:{marginBottom:12,padding:4,flexDirection:"row",gap:4,borderWidth:1,borderColor:"#d9e1dc",borderRadius:15,backgroundColor:"#fff"}, stageTab:{minHeight:40,minWidth:112,paddingHorizontal:12,alignItems:"center",justifyContent:"center",borderRadius:11}, stageTabActive:{backgroundColor:"#623756"}, stageTabText:{color:"#657873",fontSize:10,fontWeight:"700",textAlign:"center"}, stageTabTextActive:{color:"#fff"},
  stageHero:{minHeight:255,padding:24,borderRadius:28,borderBottomLeftRadius:9,backgroundColor:"#f1d8d7",marginBottom:14,overflow:"hidden"}, stageHeroGreen:{backgroundColor:"#d3e7dc"}, stageHeroSand:{backgroundColor:"#eaddcc"}, stageHeroLilac:{backgroundColor:"#e5dcea"}, stageHeroTop:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"}, stageEyebrow:{color:"#603653",fontSize:10,fontWeight:"900",letterSpacing:1.35}, stageTitle:{maxWidth:"80%",marginTop:32,color:"#43253d",fontSize:41,lineHeight:44,fontWeight:"700",letterSpacing:-1.4}, stageDetail:{maxWidth:"76%",marginTop:8,color:"#685261",fontSize:14,lineHeight:20}, heroButton:{minHeight:44,marginTop:20,alignSelf:"flex-start",justifyContent:"center"}, heroButtonText:{color:"#4c2b45",fontSize:14,fontWeight:"800"}, heroOrbOne:{position:"absolute",width:128,height:128,right:-30,bottom:-22,borderRadius:64,borderWidth:28,borderColor:"rgba(255,255,255,.27)"}, heroOrbTwo:{position:"absolute",width:14,height:14,right:52,top:86,borderRadius:7,backgroundColor:"rgba(255,255,255,.55)"},
  glyph:{width:43,height:43,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"#f1e6ee"}, glyphGreen:{backgroundColor:"#e5f1eb"}, glyphRose:{backgroundColor:"#fff0ed"}, glyphText:{color:"#65395a",fontSize:21,fontWeight:"700"}, logBlock:{paddingVertical:18,borderTopWidth:1,borderTopColor:"#e3e8e5"}, logLabel:{color:"#344d48",fontSize:13,fontWeight:"800",marginBottom:11}, wrap:{flexDirection:"row",flexWrap:"wrap",gap:7}, choice:{minHeight:40,paddingHorizontal:13,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#d9e1dc",borderRadius:22,backgroundColor:"#fbfaf7"}, choiceSelected:{borderColor:"#b98cab",backgroundColor:"#f7e7ec"}, choiceText:{color:"#5f736d",fontSize:12,fontWeight:"700"}, choiceTextSelected:{color:"#663858"}, pressed:{opacity:.72,transform:[{scale:.985}]}, moodRow:{flexDirection:"row",gap:7}, mood:{minHeight:67,flex:1,alignItems:"center",justifyContent:"center",gap:4,borderWidth:1,borderColor:"#d9e1dc",borderRadius:14,backgroundColor:"#fbfaf7"}, moodSelected:{borderColor:"#b98cab",backgroundColor:"#f7e7ec",transform:[{translateY:-2}]}, moodSymbol:{color:"#6b3a5e",fontSize:22}, moodLabel:{color:"#61746e",fontSize:10,fontWeight:"700"}, primaryButton:{minHeight:50,paddingHorizontal:17,alignItems:"center",justifyContent:"center",borderRadius:14,backgroundColor:"#603653"}, primaryButtonText:{color:"#fff",fontSize:14,fontWeight:"800",textAlign:"center"}, privateNote:{marginTop:13,flexDirection:"row",alignItems:"flex-start",gap:7}, privateNoteIcon:{color:"#17665c",fontSize:17,fontWeight:"800"}, privateNoteText:{flex:1,color:"#60736e",fontSize:11,lineHeight:16},
  insightCard:{padding:18,flexDirection:"row",alignItems:"center",gap:13,borderWidth:1,borderColor:"#dfd2e1",borderRadius:20,backgroundColor:"#f4eff5",marginBottom:14}, insightTitle:{color:"#3f2a3b",fontSize:16,lineHeight:21,fontWeight:"700"}, chevron:{color:"#6a4861",fontSize:30,fontWeight:"300"}, appointmentCard:{flexDirection:"row",alignItems:"center",gap:13}, appointmentTitle:{color:"#173b37",fontSize:17,fontWeight:"700",marginBottom:3}, privacyStrip:{padding:16,flexDirection:"row",alignItems:"flex-start",gap:10,borderWidth:1,borderColor:"#c7ddd4",borderRadius:17,backgroundColor:"#edf6f2",marginBottom:14}, privacyTitle:{color:"#173b37",fontSize:13,fontWeight:"800",marginBottom:3},
  cycleHero:{flexDirection:"row",alignItems:"center",gap:17}, cycleRing:{width:82,height:82,borderWidth:8,borderColor:"#f1deda",borderTopColor:"#d68073",borderRadius:41,alignItems:"center",justifyContent:"center"}, cycleNumber:{color:"#613757",fontSize:25,fontWeight:"800"}, cycleUnit:{color:"#836b7b",fontSize:8,fontWeight:"800",letterSpacing:1}, weekRow:{marginTop:20,flexDirection:"row",justifyContent:"space-between",gap:3}, day:{minHeight:61,flex:1,alignItems:"center",justifyContent:"center",borderRadius:22}, dayToday:{backgroundColor:"#623756"}, dayFertile:{backgroundColor:"#dceddf"}, daySelected:{borderWidth:2,borderColor:"#623756"}, dayName:{color:"#778782",fontSize:9,fontWeight:"800",marginBottom:6}, dayNumber:{color:"#314b46",fontSize:14,fontWeight:"700"}, dayTextSelected:{color:"#fff"}, legend:{marginTop:18,paddingTop:15,flexDirection:"row",flexWrap:"wrap",gap:14,borderTopWidth:1,borderTopColor:"#e1e7e3"}, legendText:{color:"#623756",fontSize:10,fontWeight:"700"}, legendTextGreen:{color:"#38705f",fontSize:10,fontWeight:"700"}, statsRow:{marginBottom:14,flexDirection:"row",borderWidth:1,borderColor:"#d9e1dc",borderRadius:20,backgroundColor:"#fff",overflow:"hidden"}, stat:{width:"33.333%",minHeight:92,padding:11,alignItems:"center",justifyContent:"center"}, statValue:{color:"#603653",fontSize:25,fontWeight:"700",textAlign:"center"}, statLabel:{width:"100%",color:"#6d7e79",fontSize:8,lineHeight:12,fontWeight:"800",textAlign:"center"}, barChart:{height:100,marginVertical:18,flexDirection:"row",alignItems:"flex-end",gap:8}, bar:{flex:1,borderRadius:6,backgroundColor:"#c6a0bc"}, disclaimer:{marginBottom:14,padding:15,flexDirection:"row",alignItems:"flex-start",gap:10,borderRadius:15,backgroundColor:"#efede7"}, disclaimerIcon:{width:22,height:22,borderRadius:11,color:"#76551a",backgroundColor:"#fff5d7",textAlign:"center",lineHeight:22,fontWeight:"900"}, disclaimerText:{flex:1,color:"#65736f",fontSize:11,lineHeight:16},
  pregnancyHero:{minHeight:284,padding:24,borderRadius:28,borderBottomLeftRadius:9,backgroundColor:"#d2e6dc",marginBottom:14,overflow:"hidden"}, pregnancyTop:{flexDirection:"row",justifyContent:"space-between"}, percentPill:{height:34,paddingHorizontal:12,justifyContent:"center",borderRadius:17,backgroundColor:"rgba(255,255,255,.62)"}, percentText:{color:"#17665c",fontSize:12,fontWeight:"900"}, pregnancyLabel:{marginTop:25,color:"#17665c",fontSize:10,fontWeight:"900",letterSpacing:1.3}, pregnancyTitle:{marginTop:8,color:"#173b37",fontSize:38,lineHeight:43,fontWeight:"700",letterSpacing:-1.2}, pregnancyDate:{marginTop:7,color:"#45635c",fontSize:14}, progress:{height:8,marginTop:25,borderRadius:4,backgroundColor:"rgba(255,255,255,.5)",overflow:"hidden"}, progressFill:{width:"61%",height:"100%",borderRadius:4,backgroundColor:"#17665c"}, pregnancyNote:{marginTop:12,color:"#58736b",fontSize:10,lineHeight:15}, planCount:{color:"#17665c",fontSize:24,fontWeight:"800"}, contactRow:{marginVertical:20,flexDirection:"row",gap:5}, contact:{width:30,height:30,flex:1,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#d7e0db",borderRadius:9}, contactDone:{borderColor:"#b9d3c8",backgroundColor:"#e6f2ed"}, contactText:{color:"#71827d",fontSize:10,fontWeight:"800"}, contactTextDone:{color:"#17665c"}, priority:{paddingVertical:12,flexDirection:"row",alignItems:"center",gap:12,borderTopWidth:1,borderTopColor:"#e1e7e3"}, priorityText:{color:"#314b46",fontSize:14,fontWeight:"700"}, dangerCard:{padding:19,flexDirection:"row",alignItems:"flex-start",gap:13,borderWidth:1,borderColor:"#e6bcb5",borderRadius:21,backgroundColor:"#fff2ef",marginBottom:14}, dangerLabel:{color:"#9b3b35",fontSize:9,fontWeight:"900",letterSpacing:1.2}, dangerTitle:{marginTop:5,color:"#642f2b",fontSize:19,fontWeight:"800"}, dangerBody:{marginTop:7,color:"#76514d",fontSize:12,lineHeight:18}, dangerButton:{minHeight:48,marginTop:15,paddingHorizontal:15,alignItems:"center",justifyContent:"center",borderRadius:13,backgroundColor:"#a33c35"}, dangerButtonText:{color:"#fff",fontSize:13,fontWeight:"800"}, urgentSheet:{padding:24,borderWidth:1,borderColor:"#e6bcb5",borderRadius:24,backgroundColor:"#fff",marginBottom:14,shadowColor:"#3b1916",shadowOpacity:.14,shadowRadius:24,shadowOffset:{width:0,height:8}}, urgentIcon:{width:48,height:48,borderRadius:16,color:"#a33c35",backgroundColor:"#fff0ed",fontSize:24,fontWeight:"900",lineHeight:48,textAlign:"center"}, urgentTitle:{marginTop:18,color:"#642f2b",fontSize:25,lineHeight:30,fontWeight:"800"}, secondaryButton:{minHeight:48,marginTop:8,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#d7dfda",borderRadius:13,backgroundColor:"#fff"}, secondaryButtonText:{color:"#344d48",fontSize:13,fontWeight:"800"}
});
